name: Govorilka
options:
  bundleIdPrefix: com.govorilka
  deploymentTarget:
    macOS: "13.0"
  xcodeVersion: "15.0"
  createIntermediateGroups: true
  generateEmptyDirectories: true

packages:
  KeyboardShortcuts:
    url: https://github.com/sindresorhus/KeyboardShortcuts
    from: "2.0.0"

targets:
  Govorilka:
    type: application
    platform: macOS
    sources:
      - Govorilka
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.govorilka.app
        PRODUCT_NAME: Govorilka
        MARKETING_VERSION: "1.3.0"
        CURRENT_PROJECT_VERSION: "9"
        INFOPLIST_FILE: Govorilka/Info.plist
        CODE_SIGN_ENTITLEMENTS: Govorilka/Govorilka.entitlements
        SWIFT_VERSION: "5.9"
        MACOSX_DEPLOYMENT_TARGET: "13.0"
        LD_RUNPATH_SEARCH_PATHS: "$(inherited) @executable_path/../Frameworks"
        ENABLE_HARDENED_RUNTIME: YES
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: "TZY7G965L4"
    dependencies:
      - package: KeyboardShortcuts
    entitlements:
      path: Govorilka/Govorilka.entitlements
      properties:
        com.apple.security.app-sandbox: true
        com.apple.security.automation.apple-events: true
        com.apple.security.device.audio-input: true
        com.apple.security.network.client: true
        com.apple.security.files.user-selected.read-write: true
    info:
      path: Govorilka/Info.plist
      properties:
        CFBundleShortVersionString: "$(MARKETING_VERSION)"
        CFBundleVersion: "$(CURRENT_PROJECT_VERSION)"
        LSUIElement: false
        NSMicrophoneUsageDescription: "Говорилка использует микрофон для записи голоса и преобразования в текст через Deepgram API"
        NSAccessibilityUsageDescription: "Говорилка использует Универсальный доступ для автоматической вставки текста в активное приложение после записи"

  GovorilkaTests:
    type: bundle.unit-test
    platform: macOS
    sources:
      - GovorilkaTests
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.govorilka.app.tests
        SWIFT_VERSION: "5.9"
        MACOSX_DEPLOYMENT_TARGET: "13.0"
        GENERATE_INFOPLIST_FILE: YES
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: "TZY7G965L4"
    dependencies:
      - target: Govorilka
